### ISSUE TITLE
Always get bad device token when send IOS notification

### ISSUE THREAD

**Issue by bretbas** [andrei-m-code/net-core-push-notifications#61]
Hello anyone. I download your project with test. I fill all settings of my apn from firebase for IOS.
Then i try to send push notification and i always get BadDeviceToken.

In the firebase console with that token i got push notification on my phone successfully.
Please, help me, what i do wrong ?

**Comment by Hamza-Hasan-Almass** [comment]
Hi , are you fix it this issue? Or you still get BadDeviceToken ? 
because i am received the same error 

thanks

**Comment by andrei-m-code** [comment]
Guys, I need some more details on that issue... would you possibly be able to test it with the source code of the lib and create a PR?

**Comment by Hamza-Hasan-Almass** [comment]
The problem is when i am using the fcm token from client side and send the push notification from firebase console directly it was send successfully but when i am using the fcm which i received from the client side i got BadDeviceToken my code is below                 var apnSettings = new ApnSettings();
                apnSettings.ServerType = ApnServerType.Production;
                apnSettings.AppBundleIdentifier = _notificationSettings.AppBundleIdentifier;
                apnSettings.P8PrivateKey = _notificationSettings.P8PrivateKey;
                apnSettings.P8PrivateKeyId = _notificationSettings.P8PrivateKeyId;
                apnSettings.TeamId = _notificationSettings.TeamId;

**Comment by Hamza-Hasan-Almass** [comment]
@andrei-m-code  Please can you tell us how can we solve this issue?
everything i set it correctly as you mentioned in the readme file but only on the iOS device i got BadDeviceToken thanks advance

**Comment by icebeam7** [comment]
@Hamza-Hasan-Almass  you don't use the FCMToken with ApnSettings because the ApnToken and the FcmToken are different. 

Check [this link](https://www.hexnode.com/blogs/comparison-apple-push-notification-service-apns-gcm-fcm-wns/)

> The device token in APNs is a 64-byte hex string, and the Device ID in FCM is a 183-byte string, containing [a-zA-Z0-9_\-] (all numbers, lowercase, and uppercase alphabets, and symbols like \, _ and –).

Examples:

FCM Token: aaa12Om83EL9r57in1cJpy:APA91bFv1ydna_52WPl34jNYAFCs-_MHcgrTjjYlg2NetJRPI71111jf4449md-WsSDHcKLWS_n6mGpTGtOZZZhQQQO7NiI65LZMmxqpFUbAivn_YRYR-cIceQH4AhFmg0muUGdlAQYt

APNs Token: 2f3035b209d30980e462a0921f4853021d7ee030e200bc0000487b9008a80005

If you use FCM token with ApnSender then you'll receive BadDeviceToken. Use APNs Token with ApnSender or FCM Token with FCMSender
